version: 2.1

jobs:
  deploy-laravel:
    docker:
      - image: circleci/php:7.4-node-browsers

    steps:
      - checkout

      - run:
          name: Install SSH
          command: apk add --no-cache openssh-client

      - add_ssh_keys:
          fingerprints:
            - $SSHKEY

      - run:
          name: Deploy to server
          command: ssh $USERNAME@$HOST "cd /home/ubuntu/devops && ./deploy.sh"
          environment:
            HOST: $HOST
            USERNAME: $USERNAME
