version: 2.1

jobs:
  deploy-laravel:
    docker:
      - image: circleci/php:7.4-node-browsers

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - $SSHKEY

      - run:
          name: Deploy to server
          command: ssh $USERNAME@$HOST "cd /home/ubuntu/devops && ./deploy.sh"

workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy-laravel:
          filters:
            branches:
              only:
                - master