version: 2.1

jobs:
  build-prod:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      
      - run:
          name: Update Package Repositories
          command: apk update

      - run:
          name: Install SSH
          command: apk add --no-cache openssh-client

      - add_ssh_keys:
          fingerprints:
            - "$SSHKEY"

      - run:
          name: Deploy to server
          command: ssh "$USERNAME@$HOST" "cd /home/ubuntu/devops && ./deploy.sh"
          environment:
            HOST: $HOST
            USERNAME: $USERNAME

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-prod:
          filters:
            branches:
              only:
                - master
