version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/php:7.2-browsers

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $SSHKEY

      - run:
          name: Deploy to server
          command: ssh $USERNAME@$HOST 'cd /home/ubuntu/devops && ./deploy.sh'

workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
